from __future__ import annotations

from dataclasses import asdict, is_dataclass
from pathlib import Path
from typing import Any

from totalsegmentator_wrapper_mac.benchmark import write_json
from totalsegmentator_wrapper_mac.mask_stats import collect_mask_stats
from totalsegmentator_wrapper_mac.outputs import CaseOutput


NON_CLINICAL_NOTICE = (
    "This is a non-clinical research/education preview. It is not a medical device "
    "and is not intended for diagnosis, treatment planning, surgical planning, or "
    "autonomous clinical decision-making. Outputs must be treated as preliminary "
    "segmentation model outputs and manually reviewed."
)


LABEL_NAMES = {
    "head": "Head",
    "mandible": "Mandible",
    "sinus_frontal": "Frontal sinus",
    "sinus_maxillary": "Maxillary sinus",
    "skull": "Skull",
    "teeth_multilabel": "Individual teeth experimental multilabel",
    "teeth_multilabel_fullspace": "Individual teeth experimental multilabel",
    "teeth_multilabel_roi": "Individual teeth experimental multilabel ROI",
    "teeth_lower": "Lower teeth",
    "teeth_upper": "Upper teeth",
}


LABEL_COLORS = {
    "head": [0.72, 0.72, 0.72],
    "mandible": [0.95, 0.78, 0.45],
    "sinus_frontal": [0.35, 0.66, 0.86],
    "sinus_maxillary": [0.25, 0.73, 0.70],
    "skull": [0.93, 0.88, 0.76],
    "teeth_multilabel": [0.92, 0.86, 0.98],
    "teeth_multilabel_fullspace": [0.92, 0.86, 0.98],
    "teeth_multilabel_roi": [0.72, 0.58, 0.80],
    "teeth_lower": [0.93, 0.93, 0.90],
    "teeth_upper": [1.0, 0.96, 0.88],
}


def generate_slicer_handoff(
    *,
    case: CaseOutput,
    source_volume_path: Path,
    task: str,
    run_result: Any,
) -> None:
    source_volume_path = source_volume_path.resolve()
    segmentations_dir = case.root / "segmentations"
    mask_stats = collect_mask_stats(segmentations_dir, recursive=True)
    write_json(case.mask_stats_path, mask_stats)
    write_json(case.label_names_path, _labels_for_existing_masks(case, LABEL_NAMES))
    write_json(case.label_colors_path, _labels_for_existing_masks(case, LABEL_COLORS))
    case.slicer_script_path.write_text(
        _slicer_script(case.root.resolve(), source_volume_path),
        encoding="utf-8",
    )
    case.readme_path.write_text(
        _readme(case, source_volume_path, task, _to_dict(run_result), mask_stats),
        encoding="utf-8",
    )


def _labels_for_existing_masks(case: CaseOutput, labels: dict[str, Any]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for path in sorted((case.root / "segmentations").rglob("*.nii.gz")):
        key = _label_key(path)
        if key in labels:
            result[key] = labels[key]
    return result


def _label_key(path: Path) -> str:
    name = path.name
    if name.endswith(".nii.gz"):
        return name[: -len(".nii.gz")]
    return path.stem


def _to_dict(value: Any) -> dict[str, Any]:
    if is_dataclass(value):
        return asdict(value)
    if isinstance(value, dict):
        return value
    return {}


def _slicer_script(case_root: Path, source_volume_path: Path) -> str:
    return f'''# Generated by TotalSegmentator Wrapper for Mac.
# Run inside 3D Slicer:
#   Slicer --python-script open_in_slicer.py

import json
from pathlib import Path

import slicer


CASE_ROOT = Path({str(case_root)!r})
SOURCE_VOLUME = Path({str(source_volume_path)!r})
SEG_DIR = CASE_ROOT / "segmentations"
LABEL_NAMES = CASE_ROOT / "slicer" / "label_names.json"
LABEL_COLORS = CASE_ROOT / "slicer" / "label_colors.json"


def label_key(path):
    name = path.name
    if name.endswith(".nii.gz"):
        return name[:-len(".nii.gz")]
    return path.stem


def load_json(path):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {{}}


def labelmap_paths():
    paths = sorted(SEG_DIR.rglob("*.nii.gz"))
    names = {{path.name for path in paths}}
    if "teeth_multilabel_fullspace.nii.gz" in names:
        paths = [
            path for path in paths
            if path.name not in {{"teeth_multilabel_roi.nii.gz"}}
        ]
    return paths


print(f"[TotalSegmentator Wrapper] Opening case: {{CASE_ROOT}}")
label_names = load_json(LABEL_NAMES)
label_colors = load_json(LABEL_COLORS)

volume_node = None
if SOURCE_VOLUME.exists():
    loaded, volume_node = slicer.util.loadVolume(str(SOURCE_VOLUME), returnNode=True)
    print(f"[TotalSegmentator Wrapper] source volume loaded: {{loaded}}")
else:
    print(f"[TotalSegmentator Wrapper] source volume not found: {{SOURCE_VOLUME}}")

loaded_labelmaps = []
for path in labelmap_paths():
    key = label_key(path)
    loaded, node = slicer.util.loadLabelVolume(str(path), returnNode=True)
    if not loaded:
        print(f"[TotalSegmentator Wrapper] failed to load labelmap: {{path}}")
        continue
    node.SetName(label_names.get(key, key))
    display = node.GetDisplayNode()
    color = label_colors.get(key)
    if display is not None and color is not None:
        display.SetColor(float(color[0]), float(color[1]), float(color[2]))
        display.SetOpacity(0.45)
    loaded_labelmaps.append(node)
    print(f"[TotalSegmentator Wrapper] loaded labelmap: {{path.name}}")

print(f"[TotalSegmentator Wrapper] Loaded labelmaps: {{len(loaded_labelmaps)}}")
print("[TotalSegmentator Wrapper] Use Segmentations or Segment Editor to convert, edit, and export if needed.")

try:
    slicer.util.selectModule("SegmentEditor")
except Exception as exc:
    print("[TotalSegmentator Wrapper] Could not switch to SegmentEditor:", exc)
'''


def _readme(
    case: CaseOutput,
    source_volume_path: Path,
    task: str,
    run_result: dict[str, Any],
    mask_stats: dict[str, Any],
) -> str:
    status = run_result.get("status", "unknown")
    elapsed = run_result.get("elapsed_seconds")
    requested_device = run_result.get("requested_device", "unknown")
    actual_device = run_result.get("actual_device", "unknown")
    elapsed_text = f"{elapsed:.2f} seconds" if isinstance(elapsed, (int, float)) else "unknown"
    mask_lines = _mask_lines(mask_stats)
    source_note = _source_note(case, source_volume_path)
    return f"""# TotalSegmentator Wrapper for Mac Output

## Run

```text
task: {task}
status: {status}
requested_device: {requested_device}
actual_device: {actual_device}
elapsed: {elapsed_text}
```

## Files

```text
source volume: {source_note}
segmentations: segmentations/
benchmark log: logs/benchmark.json
environment log: logs/environment.json
run log: logs/run.log
mask stats: logs/mask_stats.json
Slicer script: slicer/open_in_slicer.py
```

## Segmentation Masks

{mask_lines}

## Open in Slicer

```bash
Slicer --python-script slicer/open_in_slicer.py
```

The generated Slicer script loads the source volume and generated labelmaps,
including experimental teeth multilabel output when present. Convert labelmaps
to Slicer segmentations manually if needed for
editing or STL export.

## Notice

{NON_CLINICAL_NOTICE}
"""


def _source_note(case: CaseOutput, source_volume_path: Path) -> str:
    try:
        relative = source_volume_path.resolve().relative_to(case.root.resolve())
    except ValueError:
        return f"original input path referenced by Slicer script: `{source_volume_path.name}`"
    return f"`{relative}`"


def _mask_lines(mask_stats: dict[str, Any]) -> str:
    masks = mask_stats.get("masks") or []
    if not masks:
        return "- none"
    lines = []
    for item in masks:
        name = item.get("name", "unknown")
        status = item.get("status", "unknown")
        if status == "ok":
            lines.append(f"- `{name}`: {item.get('nonzero_voxels')} nonzero voxels")
        else:
            lines.append(f"- `{name}`: unreadable as NIfTI mask ({item.get('error')})")
    return "\n".join(lines)
