from __future__ import annotations

import hashlib
import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WRAPPER_LICENSE = ROOT / "LICENSE"
WRAPPER_NOTICE = ROOT / "NOTICE"
SWIFT_APP_DIR = ROOT / "native" / "macos" / "TotalSegmentatorWrapperForMac"
BUILD_SCRIPT = ROOT / "scripts" / "build_mac_app.sh"
WHEEL_BUILD_SCRIPT = ROOT / "scripts" / "build_mac_wheel.sh"
DICOM_RUNTIME_BUNDLE_SCRIPT = ROOT / "scripts" / "bundle_dicom_normalizer_runtime_macos.sh"
DMG_BUILD_SCRIPT = ROOT / "scripts" / "build_mac_dmg.sh"
NOTARIZE_SCRIPT = ROOT / "scripts" / "notarize_mac_dmg.sh"
DMG_VERIFY_SCRIPT = ROOT / "scripts" / "verify_zero_env_mac_dmg.sh"
EVIDENCE_SCRIPT = ROOT / "scripts" / "collect_test_account_install_evidence.sh"
EVIDENCE_IMPORT_SCRIPT = ROOT / "scripts" / "import_test_account_evidence.sh"
SAMPLE1_ROOT = ROOT / "resources" / "sample1"
SAMPLE1_VIEWER_HTML = SAMPLE1_ROOT / "surface_preview" / "index.html"
SAMPLE1_MANIFEST = SAMPLE1_ROOT / "sample_manifest.json"
SAMPLE1_NOTICES = SAMPLE1_ROOT / "THIRD_PARTY_NOTICES.txt"
TOTALSEGMENTATOR_LICENSE = ROOT / "resources" / "third_party" / "licenses" / "TotalSegmentator-Apache-2.0.txt"
DCM2NIIX_LICENSE = ROOT / "resources" / "third_party" / "licenses" / "dcm2niix-license.txt"
TOOTHSEG_NOTICE = ROOT / "resources" / "third_party" / "licenses" / "ToothSeg-NOTICE.txt"
DENTALSEG_NOTICE = ROOT / "resources" / "third_party" / "licenses" / "DentalSegmentator-NOTICE.txt"
MANUAL_LICENSE_OVERRIDES = ROOT / "resources" / "third_party" / "licenses" / "manual-overrides.json"
LICENSE_INVENTORY_SCRIPT = ROOT / "scripts" / "generate_third_party_license_inventory.py"
LICENSE_DISTRIBUTION_SCRIPT = ROOT / "scripts" / "verify_license_distribution.py"
TOTALSEGMENTATOR_TASK_INVENTORY = ROOT / "resources" / "third_party" / "totalsegmentator_task_inventory.json"
DICOM_RUNTIME_LICENSES = (
    "GDCM-BSD-3-Clause.txt",
    "GDCM-IJG-JPEG-README.txt",
    "OpenJPEG-BSD-2-Clause.txt",
    "CharLS-BSD-3-Clause.txt",
    "json-c-MIT.txt",
    "OpenSSL-Apache-2.0.txt",
)


class MacAppPackagingTests(unittest.TestCase):
    def test_wrapper_source_license_is_apache_2_0_with_explicit_scope(self) -> None:
        pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
        license_text = WRAPPER_LICENSE.read_text(encoding="utf-8")
        notice = WRAPPER_NOTICE.read_text(encoding="utf-8")

        self.assertIn('license = "Apache-2.0"', pyproject)
        self.assertIn('license-files = ["LICENSE", "NOTICE"]', pyproject)
        self.assertIn("setuptools>=77", pyproject)
        self.assertIn("Apache License", license_text)
        self.assertIn("TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION", license_text)
        self.assertIn("Third-party software", notice)
        self.assertIn("not relicensed", notice)
        self.assertNotIn("LicenseRef-Proprietary", pyproject + notice)

    def test_totalsegmentator_public_task_inventory_matches_runtime_allowlists(self) -> None:
        from totalsegmentator_wrapper_mac.cli import TASKS
        from totalsegmentator_wrapper_mac.setup_manager import DEFAULT_TOTALSEG_WEIGHT_TASK_IDS

        inventory = json.loads(TOTALSEGMENTATOR_TASK_INVENTORY.read_text(encoding="utf-8"))
        user_tasks = inventory["user_selectable_tasks"]
        helpers = inventory["helper_weights"]
        self.assertEqual(tuple(item["name"] for item in user_tasks), TASKS)
        self.assertEqual(
            set(DEFAULT_TOTALSEG_WEIGHT_TASK_IDS),
            {item["task_id"] for item in user_tasks} | {item["task_id"] for item in helpers},
        )
        self.assertFalse(
            any(item["requires_upstream_license_gate"] for item in [*user_tasks, *helpers])
        )
        template = json.loads((ROOT / "templates" / "model_manifest.example.json").read_text(encoding="utf-8"))
        self.assertEqual(
            [item["id"] for item in template["engines"][0]["tasks"]],
            list(TASKS),
        )

    def test_build_mac_app_script_has_expected_bundle_steps(self) -> None:
        text = BUILD_SCRIPT.read_text(encoding="utf-8")

        self.assertIn('APP_NAME="TotalSegmentator Wrapper for Mac"', text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DIST_DIR", text)
        self.assertIn('APP_DIR="${DIST_DIR}/${APP_NAME}.app"', text)
        self.assertIn('MACOS_DIR="${CONTENTS_DIR}/MacOS"', text)
        self.assertIn('RESOURCES_DIR="${CONTENTS_DIR}/Resources"', text)
        self.assertIn("SWIFT_APP_SOURCE_DIR", text)
        self.assertIn("native/macos/TotalSegmentatorWrapperForMac", text)
        self.assertIn("require_full_xcode", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_XCODE_DEVELOPER_DIR", text)
        self.assertIn("/Applications/Xcode.app/Contents/Developer", text)
        self.assertIn("export DEVELOPER_DIR", text)
        self.assertIn("xcodebuild -version", text)
        self.assertIn("Command Line Tools alone are not enough", text)
        self.assertIn("build_swiftui_frontend", text)
        self.assertIn("xcrun --sdk macosx swiftc", text)
        self.assertIn("SWIFT_MODULE_CACHE_PATH", text)
        self.assertIn("-module-cache-path", text)
        self.assertIn("-fmodules-cache-path", text)
        self.assertIn("-framework SwiftUI", text)
        self.assertIn("-target arm64-apple-macos13.0", text)
        self.assertIn("CommandBuilder.swift", text)
        self.assertIn("TotalSegmentatorWrapperForMacApp.swift", text)
        self.assertNotIn('cc "${ROOT}/templates/mac_app_' + 'entrypoint.c"', text)
        self.assertNotIn('${RESOURCES_DIR}/launcher', text)
        self.assertNotIn("launcher/mac_app_" + "launcher.py", text)
        self.assertNotIn("mac_app_" + "launcher.py", text)
        self.assertIn("resources/sample1", text)
        self.assertIn("resources/model_comparison", text)
        self.assertIn('"${RESOURCES_DIR}/model_comparison"', text)
        self.assertIn('"model_comparison": {', text)
        self.assertIn('"provenance": "model_comparison/ASSET_PROVENANCE.json"', text)
        self.assertIn('"toothseg": "model_comparison/toothseg.png"', text)
        self.assertIn("non-clinical preview", text)
        self.assertIn("sample1/surface_preview/index.html", text)
        self.assertIn("sample1/input/DZ-CBCT_jawcrop_0p5mm.nii.gz", text)
        self.assertIn("sample1/THIRD_PARTY_NOTICES.txt", text)
        for image_name in ("totalseg", "dentalseg", "individual", "toothseg"):
            with self.subTest(image_name=image_name):
                self.assertTrue((ROOT / "resources" / "model_comparison" / f"{image_name}.png").is_file())
        provenance = json.loads(
            (ROOT / "resources" / "model_comparison" / "ASSET_PROVENANCE.json").read_text(
                encoding="utf-8"
            )
        )
        self.assertFalse(provenance["apache_2_0_relicensed"])
        for image_name, metadata in provenance["files"].items():
            actual = hashlib.sha256(
                (ROOT / "resources" / "model_comparison" / image_name).read_bytes()
            ).hexdigest()
            self.assertEqual(actual, metadata["sha256"])
        self.assertIn("setup_manifest.json", text)
        self.assertIn('"ui_frontend": "swiftui"', text)
        self.assertNotIn("legacy_" + "tk_ui", text)
        self.assertIn("constraints/macos-arm64-py312.txt", text)
        self.assertIn("external_python312_required", text)
        self.assertIn("sys.base_prefix", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_ALLOW_EXTERNAL_PYTHON_RUNTIME", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_BUNDLE_PYTHON_RUNTIME_DIR", text)
        self.assertIn("bundled_python312", text)
        self.assertIn("python/cpython-3.12/bin/python3.12", text)
        self.assertIn("bundled_site_packages", text)
        self.assertIn('[[ -L "${bundled_site_packages}" && ! -e "${bundled_site_packages}" ]]', text)
        self.assertIn("xattr -cr", text)
        self.assertIn("find \"${RESOURCES_DIR}/python/cpython-3.12\" -type d", text)
        self.assertIn("find \"${RESOURCES_DIR}/python/cpython-3.12\" -type f -exec chmod a-w", text)
        self.assertIn("codesign --force --deep --sign -", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_SIGNING_MODE", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_CODESIGN_IDENTITY", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DIST_DIR", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_BUNDLE_IDENTIFIER", text)
        self.assertIn("require_developer_id_signing", text)
        self.assertIn("codesign_developer_id", text)
        self.assertIn("--timestamp", text)
        self.assertIn("--options runtime", text)
        self.assertIn("--entitlements", text)
        self.assertIn("resources/entitlements/app.entitlements", text)
        self.assertIn("resources/entitlements/python-runtime.entitlements", text)
        self.assertIn("security find-identity -v -p codesigning", text)
        self.assertIn('"signing_mode": "${SIGNING_MODE}"', text)
        self.assertIn('"bundle_identifier": ${BUNDLE_IDENTIFIER_JSON}', text)
        self.assertIn('"notarization_profile_name": ${NOTARY_PROFILE_JSON}', text)
        self.assertIn('"notarized": ${NOTARIZED_JSON}', text)
        self.assertIn('"sample1": {', text)
        self.assertIn("sha256_file", text)
        self.assertIn('BUILD_ID="${TOTALSEGMENTATOR_WRAPPER_MAC_BUILD_ID:-}"', text)
        self.assertIn('BUILD_ID="app-${APP_VERSION}-${WHEEL_SHA256:0:12}', text)
        self.assertIn("SWIFT_SOURCE_FILES", text)
        self.assertIn("SWIFT_SOURCE_SHA256", text)
        self.assertIn("swift_source_sha256", text)
        self.assertIn("wheel_sha256", text)
        self.assertIn("constraints_sha256", text)
        self.assertIn("normalizer_sha256", text)
        self.assertIn("dcm2niix_sha256", text)
        self.assertIn("dcm2niix_version", text)
        self.assertIn("dcm2niix_source", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DCM2NIIX", text)
        self.assertIn('cp "${DCM2NIIX_PATH}" "${RESOURCES_DIR}/bin/dcm2niix"', text)
        self.assertIn('cp -R "${ROOT}/build/dicom_normalizer/lib" "${RESOURCES_DIR}/bin/lib"', text)
        self.assertIn('"dicom_normalizer_libraries": "bin/lib"', text)
        self.assertIn('find "${RESOURCES_DIR}/bin/lib" -type f -name "*.dylib"', text)
        self.assertIn('"dcm2niix": "bin/dcm2niix"', text)
        self.assertIn("WRAPPER_LICENSE_PATH", text)
        self.assertIn('cp "${WRAPPER_LICENSE_PATH}" "${RESOURCES_DIR}/LICENSE"', text)
        self.assertIn('cp "${WRAPPER_NOTICE_PATH}" "${RESOURCES_DIR}/NOTICE"', text)
        self.assertIn("TOTALSEGMENTATOR_LICENSE_PATH", text)
        self.assertIn("resources/third_party/licenses/TotalSegmentator-Apache-2.0.txt", text)
        self.assertIn('cp "${TOTALSEGMENTATOR_LICENSE_PATH}" "${RESOURCES_DIR}/licenses/TotalSegmentator-Apache-2.0.txt"', text)
        self.assertIn('"totalsegmentator_license": "licenses/TotalSegmentator-Apache-2.0.txt"', text)
        self.assertIn(
            '"totalsegmentator_task_inventory": "licenses/TotalSegmentator-task-inventory.json"',
            text,
        )
        self.assertIn('cp "${TOOTHSEG_NOTICE_PATH}" "${RESOURCES_DIR}/licenses/ToothSeg-NOTICE.txt"', text)
        self.assertIn(
            'cp "${DENTALSEG_NOTICE_PATH}" "${RESOURCES_DIR}/licenses/DentalSegmentator-NOTICE.txt"',
            text,
        )
        self.assertIn('"toothseg_notice": "licenses/ToothSeg-NOTICE.txt"', text)
        self.assertIn('"dentalsegmentator_notice": "licenses/DentalSegmentator-NOTICE.txt"', text)
        self.assertIn("Separately downloaded model license: CC BY 4.0", text)
        self.assertIn("DCM2NIIX_LICENSE_PATH", text)
        self.assertIn("resources/third_party/licenses/dcm2niix-license.txt", text)
        self.assertIn('cp "${DCM2NIIX_LICENSE_PATH}" "${RESOURCES_DIR}/licenses/dcm2niix-license.txt"', text)
        self.assertIn('"dcm2niix_license": "licenses/dcm2niix-license.txt"', text)
        self.assertIn("LICENSE_MANUAL_OVERRIDES_PATH", text)
        self.assertIn("resources/third_party/licenses/manual-overrides.json", text)
        self.assertIn("generate_third_party_license_inventory.py", text)
        self.assertIn("LICENSE_INVENTORY_ENV_DIR", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_LICENSE_SITE_PATH", text)
        self.assertIn("--site-path", text)
        self.assertIn('pip install -c "${CONSTRAINTS_PATH}" "${WHEEL_PATH}[dicom,mps,dentalseg,toothseg]"', text)
        self.assertIn("--fail-on-unresolved", text)
        self.assertIn('--first-party-package "totalsegmentator-wrapper-mac"', text)
        self.assertIn('"third_party_licenses": {', text)
        self.assertIn('"inventory": "licenses/third_party_license_inventory.json"', text)
        self.assertIn('"summary": "licenses/THIRD_PARTY_LICENSES.txt"', text)
        self.assertIn('"unresolved_count": ${LICENSE_UNRESOLVED_COUNT}', text)
        self.assertIn('"third_party_license_inventory": "licenses/third_party_license_inventory.json"', text)
        self.assertIn('"third_party_license_summary": "licenses/THIRD_PARTY_LICENSES.txt"', text)
        self.assertIn('"expression": "Apache-2.0"', text)
        self.assertIn('"wrapper_license": "LICENSE"', text)
        self.assertIn('"wrapper_notice": "NOTICE"', text)
        self.assertIn("THIRD_PARTY_NOTICES.txt", text)
        self.assertIn("TotalSegmentator", text)
        self.assertIn("Apache-2.0", text)
        self.assertIn("Contents/Resources/licenses/TotalSegmentator-Apache-2.0.txt", text)
        self.assertIn("Contents/Resources/licenses/dcm2niix-license.txt", text)
        self.assertIn("Contents/Resources/licenses/third_party_license_inventory.json", text)
        self.assertIn("Contents/Resources/licenses/DentalSegmentator-NOTICE.txt", text)
        self.assertIn("Contents/Resources/LICENSE", text)
        self.assertIn("Contents/Resources/NOTICE", text)
        self.assertIn("verify_license_distribution.py", text)
        self.assertNotIn("See the upstream license.txt", text)
        self.assertIn("sample1_manifest_sha256", text)
        self.assertIn("dependency_set_id", text)
        self.assertIn("pydicom3-gdcm3.2-toothseg-acvl0.2-scipy1", text)
        self.assertIn("update_manifest_url", text)
        self.assertIn("update_allowed_hosts", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_UPDATE_ALLOWED_HOSTS", text)
        self.assertNotIn("sudo", text)
        self.assertNotIn("brew install", text)
        for license_name in DICOM_RUNTIME_LICENSES:
            with self.subTest(license_name=license_name):
                self.assertIn(license_name, text)
                license_path = ROOT / "resources" / "third_party" / "licenses" / license_name
                self.assertGreater(license_path.stat().st_size, 100)

    def test_dicom_runtime_bundle_is_self_contained_and_resigned(self) -> None:
        text = DICOM_RUNTIME_BUNDLE_SCRIPT.read_text(encoding="utf-8")

        self.assertIn("otool -L", text)
        self.assertIn("install_name_tool -change", text)
        self.assertIn("@loader_path/lib", text)
        self.assertIn("@loader_path/", text)
        self.assertIn("/opt/homebrew", text)
        self.assertIn("/usr/local", text)
        self.assertIn('codesign --force --sign - "${library}"', text)
        self.assertIn('codesign --force --sign - "${BINARY}"', text)

    def test_notarization_script_submits_staples_and_validates_dmg(self) -> None:
        text = NOTARIZE_SCRIPT.read_text(encoding="utf-8")

        self.assertIn('APP_VERSION="${TOTALSEGMENTATOR_WRAPPER_MAC_APP_VERSION:-0.2.1}"', text)
        self.assertIn('DMG_VERSION_TAG="${TOTALSEGMENTATOR_WRAPPER_MAC_DMG_VERSION_TAG:-${APP_VERSION}-20260728-surface-preview}"', text)
        self.assertIn('${APP_NAME}-${DMG_VERSION_TAG}-arm64.dmg', text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DMG_PATH", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_NOTARY_PROFILE", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_CODESIGN_IDENTITY", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_BUNDLE_IDENTIFIER", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_SIGNING_MODE=developer-id", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_NOTARIZED=1", text)
        self.assertIn("codesign --force --timestamp --sign", text)
        self.assertIn("notarytool submit", text)
        self.assertIn("--keychain-profile", text)
        self.assertIn("--wait", text)
        self.assertIn("--output-format json", text)
        self.assertIn("notary_submission.json", text)
        self.assertIn("notary_log.json", text)
        self.assertIn("stapler staple", text)
        self.assertIn("stapler validate", text)
        self.assertIn("spctl --assess --type open", text)
        self.assertIn("spctl --assess --type execute", text)
        self.assertIn("hdiutil attach", text)
        self.assertIn("notarytool history", text)
        self.assertLess(
            text.index("notarytool history"),
            text.index('TOTALSEGMENTATOR_WRAPPER_MAC_SIGNING_MODE=developer-id'),
        )
        self.assertNotIn("AuthKey_", text)
        self.assertNotIn("--password", text)

    def test_dmg_build_script_uses_configured_app_version_for_filename(self) -> None:
        text = DMG_BUILD_SCRIPT.read_text(encoding="utf-8")

        self.assertIn('APP_VERSION="${TOTALSEGMENTATOR_WRAPPER_MAC_APP_VERSION:-0.2.1}"', text)
        self.assertIn('DMG_VERSION_TAG="${TOTALSEGMENTATOR_WRAPPER_MAC_DMG_VERSION_TAG:-${APP_VERSION}-20260728-surface-preview}"', text)
        self.assertIn('${APP_NAME}-${DMG_VERSION_TAG}-arm64.dmg', text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DMG_PATH", text)
        self.assertNotIn('${APP_NAME}-0.1.0-arm64.dmg"', text)

    def test_swiftui_frontend_sources_cover_setup_main_and_safe_commands(self) -> None:
        texts = {
            path.name: path.read_text(encoding="utf-8")
            for path in sorted(SWIFT_APP_DIR.glob("*.swift"))
        }
        combined = "\n".join(texts.values())

        for name in (
            "CommandBuilder.swift",
            "ProcessSupport.swift",
            "AppState.swift",
            "Views.swift",
            "TotalSegmentatorWrapperForMacApp.swift",
        ):
            self.assertIn(name, texts)

        self.assertIn("@main", texts["TotalSegmentatorWrapperForMacApp.swift"])
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_HEADLESS", texts["TotalSegmentatorWrapperForMacApp.swift"])
        self.assertIn("SetupCoordinator.runSetup", texts["TotalSegmentatorWrapperForMacApp.swift"])
        self.assertIn("NavigationSplitView", texts["Views.swift"])
        self.assertIn("最初はSampleで流れを確認", texts["Views.swift"])
        self.assertIn("手元のCTデータを使う", texts["Views.swift"])
        self.assertIn("CTデータを選ぶ", texts["Views.swift"])
        self.assertIn("詳細ログを見る", texts["Views.swift"])
        self.assertIn("ログファイルを開く", texts["Views.swift"])
        self.assertIn("Finderで表示", texts["Views.swift"])
        self.assertIn("logInfoText", texts["Views.swift"])
        self.assertIn("state.showDetailedLog()", texts["Views.swift"])
        self.assertIn(".sheet(isPresented: $state.showLog)", texts["Views.swift"])
        self.assertNotIn("TextEditor(text: $state.logText)", texts["Views.swift"])
        self.assertIn("Sampleで3Dプレビューを作る", texts["Views.swift"])
        self.assertIn("この撮影を使う", texts["Views.swift"])
        self.assertIn("3Dプレビューを再生成", texts["Views.swift"])
        self.assertIn("保存されたファイル", texts["Views.swift"])
        self.assertIn("エラー情報をコピー", texts["Views.swift"])
        self.assertIn("DentalPreparationConfirmationSheet", texts["Views.swift"])
        self.assertIn("Process()", texts["ProcessSupport.swift"])
        self.assertIn("executableURL", texts["ProcessSupport.swift"])
        self.assertIn("arguments = Array(command.dropFirst())", texts["ProcessSupport.swift"])
        self.assertIn("SIGKILL", texts["ProcessSupport.swift"])
        self.assertIn("env/bin/TotalSegmentator", texts["CommandBuilder.swift"])
        self.assertIn('ProcessInfo.processInfo.environment["HOME"]', texts["CommandBuilder.swift"])
        self.assertIn('if python.hasPrefix("/")', texts["CommandBuilder.swift"])
        self.assertIn("inferBundleResourcesFromExecutable", texts["CommandBuilder.swift"])
        self.assertIn("Bundle.main.executableURL", texts["CommandBuilder.swift"])
        self.assertIn("resourcesURL(fromBundle", texts["CommandBuilder.swift"])
        self.assertIn("_NSGetExecutablePath", texts["CommandBuilder.swift"])
        self.assertIn("resourcesURL(fromExecutable", texts["CommandBuilder.swift"])
        self.assertIn('"Contents"', texts["CommandBuilder.swift"])
        self.assertIn('"Resources"', texts["CommandBuilder.swift"])
        self.assertIn('"Library/Application Support"', texts["CommandBuilder.swift"])
        self.assertIn('"--totalseg-bin"', texts["CommandBuilder.swift"])
        self.assertIn('"--skip-dentalseg-model"', texts["CommandBuilder.swift"])
        self.assertIn('"--execution-profile"', texts["CommandBuilder.swift"])
        self.assertIn('"macos-app"', texts["CommandBuilder.swift"])
        self.assertIn('"--require-mps"', texts["CommandBuilder.swift"])
        self.assertIn('"--device"', texts["CommandBuilder.swift"])
        self.assertIn('"mps"', texts["CommandBuilder.swift"])
        self.assertIn('env.removeValue(forKey: "PYTORCH_ENABLE_MPS_FALLBACK")', texts["CommandBuilder.swift"])
        self.assertIn("dentalsegStatusCommand", texts["CommandBuilder.swift"])
        self.assertIn("dentalsegPrepareCommand", texts["CommandBuilder.swift"])
        self.assertIn('"dentalseg-status"', texts["CommandBuilder.swift"])
        self.assertIn('"dentalseg-prepare"', texts["CommandBuilder.swift"])
        self.assertIn("toothsegStatusCommand", texts["CommandBuilder.swift"])
        self.assertIn("toothsegPrepareCommand", texts["CommandBuilder.swift"])
        self.assertIn('"toothseg-status"', texts["CommandBuilder.swift"])
        self.assertIn('"toothseg-prepare"', texts["CommandBuilder.swift"])
        self.assertIn('"--toothseg-nnunet-results"', texts["CommandBuilder.swift"])
        self.assertIn('"--robust-crop"', texts["CommandBuilder.swift"])
        self.assertIn('"--higher-order-resampling"', texts["CommandBuilder.swift"])
        self.assertIn('"--teeth-robust-craniofacial-preflight"', texts["CommandBuilder.swift"])
        self.assertIn("dicom-normalizer-audit", texts["CommandBuilder.swift"])
        self.assertIn("dicom-normalizer-convert-clean", texts["CommandBuilder.swift"])
        self.assertIn("var dcm2niix: URL", texts["CommandBuilder.swift"])
        self.assertIn('"--dcm2niix"', texts["CommandBuilder.swift"])
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DCM2NIIX", texts["CommandBuilder.swift"])
        self.assertNotIn("/opt/homebrew/bin", texts["CommandBuilder.swift"])
        self.assertNotIn("/usr/local/bin", texts["CommandBuilder.swift"])
        self.assertIn('"--timeout-sec"', texts["CommandBuilder.swift"])
        self.assertIn('"120"', texts["CommandBuilder.swift"])
        self.assertIn("surface-preview", texts["CommandBuilder.swift"])
        self.assertIn("surfacePreviewCommand", texts["CommandBuilder.swift"])
        self.assertIn("slicer-export", texts["CommandBuilder.swift"])
        self.assertIn("slicerExportCommand", texts["CommandBuilder.swift"])
        self.assertIn("update-check", texts["CommandBuilder.swift"])
        self.assertIn("updateCheckRunning", texts["AppState.swift"])
        self.assertIn("updateInstallRunning", texts["AppState.swift"])
        self.assertIn("configure_totalseg_privacy", texts["CommandBuilder.swift"])
        self.assertIn("download_totalseg_weights", texts["CommandBuilder.swift"])
        self.assertIn("download_dentalseg_weights", texts["CommandBuilder.swift"])
        self.assertIn("weights_download_failed", texts["CommandBuilder.swift"])
        self.assertIn("dentalseg_weights_download_failed", texts["CommandBuilder.swift"])
        self.assertIn("利用状況データ", texts["CommandBuilder.swift"])
        self.assertIn("totalseg_privacy_config_failed", texts["CommandBuilder.swift"])
        self.assertIn("setupRecoverySuggestion", texts["CommandBuilder.swift"])
        self.assertIn("let updateRunner = ProcessRunner()", texts["AppState.swift"])
        self.assertIn("downloadAndInstallPendingUpdate", texts["AppState.swift"])
        self.assertIn("pendingUpdateSHA256", texts["AppState.swift"])
        self.assertIn("sha256Hex", texts["AppState.swift"])
        self.assertIn("writeUpdateInstallerScript", texts["AppState.swift"])
        self.assertIn('setupMessage = "アプリ更新の反映が必要です。準備を始めるまで通信しません。"', texts["AppState.swift"])
        self.assertIn("startSetup()", texts["AppState.swift"])
        self.assertIn("spctl --assess --type execute", texts["AppState.swift"])
        self.assertIn("/usr/bin/ditto", texts["AppState.swift"])
        self.assertIn("update-backup", texts["AppState.swift"])
        self.assertIn("venvPythonMatchesBundle", texts["ProcessSupport.swift"])
        self.assertIn("venv_python_changed", texts["ProcessSupport.swift"])
        self.assertIn("removeItem(at: paths.support.appendingPathComponent(\"env\"", texts["ProcessSupport.swift"])
        self.assertIn('reason: "legacy_setup_state"', texts["ProcessSupport.swift"])
        self.assertIn('action: "setup_required"', texts["ProcessSupport.swift"])
        self.assertIn("/bin/chmod -R u+w", texts["AppState.swift"])
        self.assertIn("/bin/mv \"$APP\" \"$BACKUP\"", texts["AppState.swift"])
        self.assertIn("更新をインストール", texts["Views.swift"])
        self.assertIn("enum InputSource", texts["AppState.swift"])
        self.assertIn("canStartSampleRun", texts["AppState.swift"])
        self.assertIn("canStartOwnDataRun", texts["AppState.swift"])
        self.assertIn("canUseSelectedDicomSeries", texts["AppState.swift"])
        self.assertIn("dicomCleanCandidates", texts["AppState.swift"])
        self.assertIn("convertDicomToNiftiFromAudit", texts["AppState.swift"])
        self.assertIn("cleanDicomSeriesCandidates", texts["AppState.swift"])
        self.assertIn("convertedNiftiURL", texts["AppState.swift"])
        self.assertIn("ownDataPrimaryButtonTitle", texts["AppState.swift"])
        self.assertIn("inputSource == .dicomFolder || isDirectory(inputURL)", texts["AppState.swift"])
        self.assertIn("guard inputSource == .sample || inputSource == .nifti", texts["AppState.swift"])
        self.assertIn("let output = nextCaseOutput()", texts["AppState.swift"])
        self.assertIn("regenerateSurfacePreview", texts["AppState.swift"])
        self.assertIn("labelmap作成は再実行せず", texts["AppState.swift"])
        self.assertIn("stopRequested", texts["AppState.swift"])
        self.assertIn("停止要求済み", texts["AppState.swift"])
        self.assertIn("showingUpdateConfirmation", texts["AppState.swift"])
        self.assertIn("confirmOpenPendingDownload", texts["AppState.swift"])
        self.assertIn("pendingDownloadURL = nil", texts["AppState.swift"])
        self.assertIn("stoppedBeforeSummary", texts["AppState.swift"])
        self.assertIn("runner.resetTerminationRequest()", texts["AppState.swift"])
        self.assertNotIn("rc == 0 && modeForRun == .individualTeeth", texts["AppState.swift"])
        self.assertIn("歯列・顎骨", texts["AppState.swift"])
        self.assertIn("CommandBuilder.surfacePreviewCommand", texts["AppState.swift"])
        self.assertIn("CommandBuilder.slicerExportCommand", texts["AppState.swift"])
        self.assertIn("Slicerで開けるファイルを書き出しました", texts["AppState.swift"])
        self.assertIn("3D Slicer用に書き出す", texts["Views.swift"])
        self.assertIn("3Dプレビュー作成中", texts["AppState.swift"])
        self.assertIn("3Dプレビューを作成しました", texts["AppState.swift"])
        self.assertIn("3Dプレビュー生成に失敗しました", texts["AppState.swift"])
        self.assertIn("runProgressFromLog", texts["AppState.swift"])
        self.assertIn("runProgressFraction", texts["AppState.swift"])
        self.assertIn("toothSegPreparationProgressFromLog", texts["AppState.swift"])
        self.assertIn("dentalPreparationFraction", texts["Views.swift"])
        self.assertIn("残り約", texts["AppState.swift"])
        self.assertIn("RUN_PROGRESS ", texts["AppState.swift"])
        self.assertIn("LOG_TAIL_BYTES", texts["AppState.swift"])
        self.assertIn("readLogTail", texts["AppState.swift"])
        self.assertIn("openCurrentLogFile", texts["AppState.swift"])
        self.assertIn("openCurrentLogFolder", texts["AppState.swift"])
        self.assertIn("showDetailedLog", texts["AppState.swift"])
        self.assertIn("let target = url ?? currentLogURL", texts["AppState.swift"])
        self.assertIn("最後の一部だけ表示", texts["AppState.swift"])
        self.assertIn("stage: stringFromJSON", texts["AppState.swift"])
        self.assertIn("percent == 100", texts["AppState.swift"])
        self.assertIn("次の処理へ進んでいます", texts["AppState.swift"])
        self.assertIn("runHeartbeatText", texts["AppState.swift"])
        self.assertIn("lastRunProgressAt", texts["AppState.swift"])
        self.assertIn("lastRunProgressSignature", texts["AppState.swift"])
        self.assertIn("updateRunHeartbeat", texts["AppState.swift"])
        self.assertIn("最終更新:", texts["AppState.swift"])
        self.assertIn("大きなデータではこの待ち時間が発生します", texts["AppState.swift"])
        self.assertIn("ProgressView()", texts["Views.swift"])
        self.assertIn("ProgressView(value: fraction)", texts["Views.swift"])
        self.assertIn("Text(heartbeatText)", texts["Views.swift"])
        self.assertIn("別のCTを選ぶ", texts["Views.swift"])
        self.assertNotIn("NIfTIへ変換して入力に使う", texts["Views.swift"])
        self.assertIn("もう一度作成", texts["Views.swift"])
        self.assertIn("もう一度実行", texts["AppState.swift"])
        self.assertIn("もう一度確認", texts["AppState.swift"])
        self.assertIn("canRetryFromResult", texts["AppState.swift"])
        self.assertIn("lastDicomDirURL != nil", texts["AppState.swift"])
        self.assertIn("最初に戻る", texts["Views.swift"])
        self.assertIn("goToInput", texts["AppState.swift"])
        self.assertIn("goToStart", texts["AppState.swift"])
        self.assertIn("goToSample", texts["AppState.swift"])
        self.assertIn("goToOwnData", texts["AppState.swift"])
        self.assertIn("retryRunFromResult", texts["AppState.swift"])
        self.assertIn("resultKind == .dicomAudit", texts["AppState.swift"])
        self.assertIn("runDicomAudit(dicomDir: lastDicomDirURL)", texts["AppState.swift"])
        self.assertIn("isDirectory(inputURL)", texts["AppState.swift"])
        self.assertIn("contentShape(Rectangle())", texts["Views.swift"])
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DICOM_NORMALIZER", texts["CommandBuilder.swift"])
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DCM2NIIX", texts["CommandBuilder.swift"])
        self.assertIn("外部へ送信しません", texts["Views.swift"])
        self.assertIn("DentalPreparationConfirmationSheet", texts["Views.swift"])
        self.assertIn("追加モデルデータを取得するので少し時間がかかります。", texts["Views.swift"])
        self.assertIn("setupReasonToJapanese", texts["CommandBuilder.swift"])
        self.assertNotIn("shell=True", combined)
        self.assertNotIn("/usr/bin/env python3", combined)

    def test_bundled_sample1_viewer_is_offline_html(self) -> None:
        text = SAMPLE1_VIEWER_HTML.read_text(encoding="utf-8")

        self.assertIn("TotalSegmentator 3Dビューアー", text)
        self.assertIn("const DATA =", text)
        self.assertIn('"dataLabel":"付属サンプル"', text)
        self.assertNotIn("teeth_multilabel_fullspace.nii.gz", text)
        self.assertIn("modeTrackpad", text)
        self.assertIn("トラックパッド", text)
        self.assertIn("マウス", text)
        self.assertIn("全体に合わせる", text)
        self.assertIn("表面平滑化", text)
        self.assertIn("ポリゴン数", text)
        self.assertIn("歯髄腔（推定）", text)
        self.assertNotIn("http://", text)
        self.assertNotIn("https://", text)
        self.assertNotIn("cdn", text.lower())
        self.assertNotIn("<script src=", text.lower())

    def test_bundled_sample1_manifest_and_notices_document_license_and_purpose(self) -> None:
        manifest = json.loads(SAMPLE1_MANIFEST.read_text(encoding="utf-8"))
        notices = SAMPLE1_NOTICES.read_text(encoding="utf-8")
        license_text = TOTALSEGMENTATOR_LICENSE.read_text(encoding="utf-8")

        self.assertEqual(manifest["sample_id"], "sample1_dz_cbct_jawcrop_0p5mm")
        self.assertEqual(manifest["default_input"], "input/DZ-CBCT_jawcrop_0p5mm.nii.gz")
        self.assertEqual(manifest["surface_preview"], "surface_preview/index.html")
        self.assertEqual(manifest["expected_runtime_seconds_approx"], 100)
        self.assertIn("100秒前後", manifest["expected_runtime_note_ja"])
        self.assertFalse(manifest["clinical_use"])
        self.assertIn("CBCT-MR Head", notices)
        self.assertIn("unrestricted", notices)
        self.assertIn("4ce7aa75278b5a7b757ed0c8d7a6b3caccfc3e2973b020532456dbc8f3def7db", notices)
        self.assertIn("TotalSegmentator", notices)
        self.assertIn("Apache License 2.0", notices)
        self.assertIn("Contents/Resources/licenses/TotalSegmentator-Apache-2.0.txt", notices)
        self.assertIn("not for diagnosis", notices)
        self.assertIn("Apache License", license_text)
        self.assertIn("TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION", license_text)
        self.assertIn("Redistribution", license_text)
        for relative, metadata in manifest["derived_files"].items():
            with self.subTest(relative=relative):
                actual = hashlib.sha256((SAMPLE1_ROOT / relative).read_bytes()).hexdigest()
                self.assertEqual(actual, metadata["sha256"])
                self.assertIn(actual, notices)

    def test_static_third_party_license_files_are_present(self) -> None:
        dcm2niix_license = DCM2NIIX_LICENSE.read_text(encoding="utf-8")
        toothseg_notice = TOOTHSEG_NOTICE.read_text(encoding="utf-8")
        dentalseg_notice = DENTALSEG_NOTICE.read_text(encoding="utf-8")
        manual_overrides = json.loads(MANUAL_LICENSE_OVERRIDES.read_text(encoding="utf-8"))
        inventory_script = LICENSE_INVENTORY_SCRIPT.read_text(encoding="utf-8")
        override_keys = {
            (item["package"], item["version"], item["decision"])
            for item in manual_overrides["overrides"]
        }

        self.assertIn("Copyright (c) 2014-2025 Chris Rorden", dcm2niix_license)
        self.assertIn("Redistribution and use in source and binary forms", dcm2niix_license)
        self.assertIn("10.5281/zenodo.14893540", toothseg_notice)
        self.assertIn("CC BY 4.0", toothseg_notice)
        for creator in (
            "Fabian Isensee",
            "Niels van Nistelrooij",
            "Lars Krämer",
            "Shankeeth Vinayahalingam",
        ):
            self.assertIn(creator, toothseg_notice)
        self.assertIn("https://creativecommons.org/licenses/by/4.0/", toothseg_notice)
        self.assertIn("Changes made by this project", toothseg_notice)
        self.assertNotIn("Copyright (c) 2026", toothseg_notice)
        self.assertIn("10.5281/zenodo.10829675", dentalseg_notice)
        self.assertIn("Gauthier Dot", dentalseg_notice)
        self.assertIn("https://creativecommons.org/licenses/by/4.0/", dentalseg_notice)
        self.assertIn("checkpoint parameters are not modified", dentalseg_notice)
        self.assertEqual(
            manual_overrides["schema"],
            "totalsegmentator_wrapper_mac.manual_license_overrides.v1",
        )
        self.assertIn(("argparse", "1.4.0", "accepted"), override_keys)
        self.assertIn(("linecache2", "1.0.0", "accepted"), override_keys)
        self.assertIn(("traceback2", "1.4.0", "accepted"), override_keys)
        self.assertIn(("unittest2", "1.1.0", "accepted"), override_keys)
        self.assertIn(("connected-components-3d", "4.0.0", "accepted"), override_keys)
        self.assertIn(("pandas", "3.0.3", "accepted"), override_keys)
        self.assertIn(("matplotlib", "3.11.0", "accepted"), override_keys)
        self.assertIn(("scipy", "1.17.1", "accepted"), override_keys)
        self.assertIn(("scipy", "1.18.0", "accepted"), override_keys)
        self.assertNotIn(("totalsegmentator-wrapper-mac", "0.2.1", "accepted"), override_keys)
        self.assertIn("third_party_license_inventory.v1", inventory_script)
        self.assertIn("attention_license_requires_review", inventory_script)
        self.assertIn("license_metadata_unknown", inventory_script)
        self.assertIn("license_text_missing", inventory_script)

    def test_distribution_license_verifier_checks_wheel_app_and_dmg(self) -> None:
        text = LICENSE_DISTRIBUTION_SCRIPT.read_text(encoding="utf-8")

        self.assertIn("License-Expression: Apache-2.0", text)
        self.assertIn("verify_wheel", text)
        self.assertIn("verify_app", text)
        self.assertIn("verify_dmg", text)
        self.assertIn("LicenseRef-Proprietary", text)
        self.assertIn("unmapped native library", text)

    def test_bundled_sample1_metadata_does_not_expose_developer_local_paths(self) -> None:
        checked = [
            *sorted((SAMPLE1_ROOT / "logs").glob("*.json")),
            SAMPLE1_ROOT / "surface_preview" / "preview_summary.json",
        ]
        self.assertTrue(checked)
        for path in checked:
            text = path.read_text(encoding="utf-8")
            with self.subTest(path=path.name):
                self.assertNotIn("/Users/ainem", text)
                self.assertNotIn("segmentation_w_mps", text)
                self.assertNotIn(".venv", text)

    def test_build_mac_wheel_uses_pep517_frontend(self) -> None:
        text = WHEEL_BUILD_SCRIPT.read_text(encoding="utf-8")

        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DIST_DIR", text)
        self.assertIn("uv is required", text)
        self.assertIn("UV_CACHE_DIR", text)
        self.assertIn("SOURCE_DATE_EPOCH", text)
        self.assertIn("build --wheel --no-build-isolation", text)
        self.assertIn("--python \"${PYTHON_BIN}\"", text)
        self.assertIn("--no-build-isolation", text)
        self.assertIn("--config-setting=\"--build-option=--plat-name\"", text)
        self.assertIn("BinaryDistribution", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_SIGNING_MODE", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_CODESIGN_IDENTITY", text)
        self.assertIn("codesign \\", text)
        self.assertIn("--timestamp", text)
        self.assertIn("--options runtime", text)
        self.assertIn("src/totalsegmentator_wrapper_mac/bin/totalsegmentator-wrapper-dicom-normalizer", text)
        self.assertIn('cp -R "${NATIVE_BUILD_DIR}/lib"', text)
        self.assertIn('bin/lib"/*.dylib', text)
        self.assertIn('src/totalsegmentator_wrapper_mac/licenses', text)
        for license_name in DICOM_RUNTIME_LICENSES:
            with self.subTest(license_name=license_name):
                self.assertIn(license_name, text)
        self.assertNotIn("setup.py bdist_wheel", text)
        self.assertNotIn("from wheel.bdist_wheel", text)

    def test_mac_constraints_use_pydicom3_for_dicom2nifti(self) -> None:
        constraints = (ROOT / "constraints" / "macos-arm64-py312.txt").read_text(encoding="utf-8")
        pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")

        self.assertIn("pydicom>=3,<4", constraints)
        self.assertIn("nnunetv2==2.8.1", constraints)
        self.assertIn('"pydicom>=3,<4"', pyproject)
        self.assertIn('"nnunetv2>=2.8.1,<2.9"', pyproject)
        self.assertNotIn("pydicom>=2.4,<3", constraints)

    def test_dmg_scripts_support_user_local_install_validation(self) -> None:
        build_text = DMG_BUILD_SCRIPT.read_text(encoding="utf-8")
        verify_text = DMG_VERIFY_SCRIPT.read_text(encoding="utf-8")

        self.assertIn("hdiutil create", build_text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_SKIP_APP_BUILD", build_text)
        self.assertIn('scripts/build_mac_app.sh', build_text)
        self.assertIn("chmod -R u+rwX", build_text)
        self.assertIn('ditto "${APP_PATH}" "${DMG_STAGING}/${APP_NAME}.app"', build_text)
        self.assertIn('cp "${ROOT}/LICENSE" "${DMG_STAGING}/LICENSE.txt"', build_text)
        self.assertIn('cp "${ROOT}/NOTICE" "${DMG_STAGING}/NOTICE.txt"', build_text)
        self.assertIn("README.txt", build_text)
        self.assertIn("TEST_ACCOUNT_INSTALL.txt", build_text)
        self.assertIn("ln -s /Applications", build_text)
        self.assertIn("Verify Test Account Install.command", build_text)
        self.assertIn("collect_test_account_install_evidence.sh", build_text)
        self.assertIn("Collect TotalSegmentator Wrapper Logs.command", build_text)
        self.assertIn("collect_launch_debug_logs.sh", build_text)
        self.assertIn("/Users/Shared/TotalSegmentatorWrapperMac", build_text)
        self.assertIn("セットアップ開始", build_text)
        self.assertIn("3Dサンプルを開く", build_text)
        self.assertIn("同梱Sample 1のオフライン3Dプレビュー", build_text)
        self.assertIn("同梱Sample 1のCT入力", build_text)
        self.assertIn("100秒前後", build_text)
        self.assertIn("モデル準備済みの場合", build_text)
        self.assertIn("利用状況データ", build_text)
        self.assertIn("セットアップ中もプレビュー作成中も送信しません", build_text)
        self.assertIn("表示用の断面画像", build_text)
        self.assertIn("CT画像そのものが壊れているとは限りません", build_text)
        self.assertIn("CTを書き出したソフト名", build_text)
        self.assertIn("ログにはローカルパス", build_text)
        self.assertIn("更新を確認", build_text)
        self.assertIn("起動時やSetup中に自動確認しません", build_text)
        self.assertIn("notarized DMGをダウンロード", build_text)
        self.assertIn("SHA256とGatekeeper確認", build_text)
        self.assertIn("アプリを置き換えて再起動", build_text)
        self.assertIn("THIRD_PARTY_NOTICES.txt", build_text)
        self.assertIn("Apache-2.0", build_text)
        self.assertIn("TotalSegmentator Apache-2.0ライセンス本文", build_text)
        self.assertIn("Contents/Resources/licenses/TotalSegmentator-Apache-2.0.txt", build_text)
        self.assertIn("Contents/Resources/licenses/dcm2niix-license.txt", build_text)
        self.assertIn("Contents/Resources/licenses/third_party_license_inventory.json", build_text)
        self.assertIn("Contents/Resources/licenses/DentalSegmentator-NOTICE.txt", build_text)
        self.assertIn("Contents/Resources/licenses/ToothSeg-NOTICE.txt", build_text)
        self.assertIn("verify_license_distribution.py", build_text)
        self.assertIn("精度評価用データではありません", build_text)
        self.assertIn("管理者権限", build_text)
        self.assertIn("DICOM、CT", build_text)
        self.assertIn("Controlキー", build_text)
        self.assertIn("MANIFEST_NOTARIZED", build_text)
        self.assertIn("notarized済みDMG", build_text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_ALLOW_ZERO_ENV_EVIDENCE", build_text)
        self.assertIn("hdiutil attach", verify_text)
        self.assertIn('ditto "${MOUNT_ROOT}/TotalSegmentator Wrapper for Mac.app"', verify_text)
        self.assertIn("README.txt", verify_text)
        self.assertIn("TEST_ACCOUNT_INSTALL.txt", verify_text)
        self.assertIn("Verify Test Account Install.command", verify_text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_ALLOW_ZERO_ENV_EVIDENCE", verify_text)
        self.assertIn('${TEST_HOME}/Applications', verify_text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_HEADLESS=1", verify_text)
        self.assertIn('"status": "success"', verify_text)
        self.assertIn('"actual_device": "mps"', verify_text)
        self.assertIn('"normalizer_source": "app_bundle"', verify_text)
        self.assertIn("Library/Caches/pip", verify_text)
        self.assertIn("cache/pycache", verify_text)
        self.assertIn("collect_test_account_install_evidence.sh", verify_text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_SHARED_EVIDENCE_DIR", verify_text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DMG_PATH", verify_text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_EXPECTED_APP_VERSION", verify_text)
        self.assertIn("0.2.1", verify_text)
        self.assertIn("0.2.1-20260728-surface-preview-arm64.dmg", verify_text)
        self.assertIn("SharedEvidence/test_account_install_evidence.json", verify_text)
        self.assertNotIn("sudo", build_text + verify_text)
        self.assertNotIn("brew install", build_text + verify_text)
        self.assertNotIn("/opt/homebrew", build_text + verify_text)

    def test_test_account_evidence_script_checks_distribution_invariants(self) -> None:
        text = EVIDENCE_SCRIPT.read_text(encoding="utf-8")

        self.assertIn("test_account_install_evidence.json", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_SHARED_EVIDENCE_DIR", text)
        self.assertIn("/Users/Shared/TotalSegmentatorWrapperMac", text)
        self.assertIn("shared_copy_path", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_DMG_PATH", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_EXPECTED_APP_VERSION", text)
        self.assertIn("manifest_app_version_matches_expected", text)
        self.assertIn("spctl_app_accepted", text)
        self.assertIn("stapler_dmg_valid", text)
        self.assertIn("manifest_notarized", text)
        self.assertIn('"--assess"', text)
        self.assertIn("stapler", text)
        self.assertIn("setup_state_success", text)
        self.assertIn("mps_actual_device", text)
        self.assertIn("mps_gate_pass", text)
        self.assertIn("normalizer_from_app_bundle", text)
        self.assertIn("python_executable_inside_app", text)
        self.assertIn("app_support_inside_current_home", text)
        self.assertIn("no_user_global_pip_cache", text)
        self.assertIn("pip_cache_under_app_support", text)
        self.assertIn("pycache_under_app_support", text)
        self.assertIn("manifest_ui_frontend_swiftui", text)
        self.assertIn("manifest_bundled_python312", text)
        self.assertIn("bundled_python_has_no_absolute_symlinks", text)
        self.assertIn("manifest_includes_sample1", text)
        self.assertIn("manifest_has_{manifest_field}", text)
        self.assertIn("wheel_sha256", text)
        self.assertIn("dcm2niix_sha256", text)
        self.assertIn("dcm2niix_version", text)
        self.assertIn("dcm2niix_source", text)
        self.assertIn("third_party_licenses", text)
        self.assertIn("bundled_dcm2niix_exists", text)
        self.assertIn("manifest_license_apache_2_0", text)
        self.assertIn("wrapper_license_exists", text)
        self.assertIn("wrapper_notice_exists", text)
        self.assertIn("totalsegmentator_license_exists", text)
        self.assertIn("dentalsegmentator_notice_exists", text)
        self.assertIn("toothseg_notice_exists", text)
        self.assertIn("dcm2niix_license_exists", text)
        self.assertIn("license_inventory_exists", text)
        self.assertIn("license_inventory_unresolved_zero", text)
        self.assertIn("license_surfaces_no_old_first_party_markers", text)
        self.assertIn("update_allowed_hosts", text)
        self.assertIn("sample1_input_exists", text)
        self.assertIn("sample1_surface_preview_exists", text)
        self.assertIn("sample1_manifest_non_clinical", text)
        self.assertIn("setup_state_installed_bundle_current", text)
        self.assertIn("Setup状態ファイルが見つかりません", text)
        self.assertIn("共有受け渡し用コピーを書き出しました", text)
        self.assertNotIn("sudo", text)
        self.assertNotIn("brew", text)

    def test_test_account_evidence_import_script_requires_all_checks(self) -> None:
        text = EVIDENCE_IMPORT_SCRIPT.read_text(encoding="utf-8")

        self.assertIn("test_account_install_verdict.json", text)
        self.assertIn("artifacts", text)
        self.assertIn("test_account_install", text)
        self.assertIn("missing_checks", text)
        self.assertIn("failed_checks", text)
        self.assertIn("home_failures", text)
        self.assertIn("evidence_home_is_temporary", text)
        self.assertIn("evidence_home_is_current_development_home", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_ALLOW_ZERO_ENV_EVIDENCE", text)
        self.assertIn("TOTALSEGMENTATOR_WRAPPER_MAC_EXPECTED_APP_VERSION", text)
        self.assertIn("manifest_app_version_matches_expected", text)
        self.assertIn("expected_app_version", text)
        self.assertIn("pycache_under_app_support", text)
        self.assertIn("manifest_ui_frontend_swiftui", text)
        self.assertIn("manifest_notarized", text)
        self.assertIn("app_codesign_valid", text)
        self.assertIn("spctl_app_accepted", text)
        self.assertIn("stapler_dmg_valid", text)
        self.assertIn("setup_state_installed_bundle_current", text)
        self.assertIn("manifest_has_update_allowed_hosts", text)
        self.assertIn("manifest_has_third_party_licenses", text)
        self.assertIn("manifest_has_dcm2niix_sha256", text)
        self.assertIn("manifest_has_dcm2niix_version", text)
        self.assertIn("manifest_has_dcm2niix_source", text)
        self.assertIn("bundled_dcm2niix_exists", text)
        self.assertIn("manifest_license_apache_2_0", text)
        self.assertIn("wrapper_license_exists", text)
        self.assertIn("wrapper_notice_exists", text)
        self.assertIn("dentalsegmentator_notice_exists", text)
        self.assertIn("toothseg_notice_exists", text)
        self.assertIn("license_inventory_unresolved_zero", text)
        self.assertIn("license_surfaces_no_old_first_party_markers", text)
        self.assertNotIn("sudo", text)
        self.assertNotIn("brew", text)

if __name__ == "__main__":
    unittest.main()
